name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64/v8 . --file Dockerfile --tag spookbot:$(date +%s)
